Fix build with clang 15
The -Wstrict-prototype got stricter with clang 15. This causes build
failures due to two missing void.

```
/tmp/pobj/liblinphone-5.1.56/liblinphone-5.1.56/console/linphonec.c:968:21: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
linphonec_idle_call ()
                    ^
                     void
```